// DOM Elements
export const elements = {
    uploadArea: document.getElementById('uploadArea'),
    fileInput: document.getElementById('fileInput'),
    mainContent: document.getElementById('mainContent'),
    loading: document.getElementById('loading'),
    previewCanvas: document.getElementById('previewCanvas'),
    paletteGrid: document.getElementById('paletteGrid'),
    colorCount: document.getElementById('colorCount'),
    frameInfo: document.getElementById('frameInfo'),
    playPauseBtn: document.getElementById('playPauseBtn'),
    prevFrameBtn: document.getElementById('prevFrameBtn'),
    nextFrameBtn: document.getElementById('nextFrameBtn'),
    exportBtn: document.getElementById('exportBtn'),
    exportPngBtn: document.getElementById('exportPngBtn'),
    originalColorEl: document.getElementById('originalColor'),
    originalColorHex: document.getElementById('originalColorHex'),
    originalColorLabel: document.getElementById('originalColorLabel'),
    newColorPicker: document.getElementById('newColorPicker'),
    applySwapBtn: document.getElementById('applySwapBtn'),
    resetBtn: document.getElementById('resetBtn'),
    zoomSlider: document.getElementById('zoomSlider'),
    zoomValue: document.getElementById('zoomValue'),
    exportPresetBtn: document.getElementById('exportPresetBtn'),
    importPresetBtn: document.getElementById('importPresetBtn'),
    importPresetInput: document.getElementById('importPresetInput'),
    swapHistoryEl: document.getElementById('swapHistory'),
    speedSlider: document.getElementById('speedSlider'),
    speedValue: document.getElementById('speedValue'),
    paletteSourceUpload: document.getElementById('paletteSourceUpload'),
    paletteSourceInput: document.getElementById('paletteSourceInput'),
    paletteSourceContent: document.getElementById('paletteSourceContent'),
    sourcePaletteContainer: document.getElementById('sourcePaletteContainer'),
    sourcePaletteGrid: document.getElementById('sourcePaletteGrid'),
    clearPaletteSourceBtn: document.getElementById('clearPaletteSourceBtn'),
    newColorHex: document.getElementById('newColorHex'),
    projectNameInput: document.getElementById('projectNameInput'),

    // Selection tool elements
    selectionCanvas: document.getElementById('selectionCanvas'),
    toolNoneBtn: document.getElementById('toolNone'),
    toolRectBtn: document.getElementById('toolRect'),
    toolPolyBtn: document.getElementById('toolPoly'),
    selectionInfo: document.getElementById('selectionInfo'),
    invertSelectionBtn: document.getElementById('invertSelectionBtn'),
    clearSelectionBtn: document.getElementById('clearSelectionBtn'),

    // Color grouping elements
    groupingToggle: document.getElementById('groupingToggle'),
    groupingThresholdContainer: document.getElementById('groupingThresholdContainer'),
    groupingThreshold: document.getElementById('groupingThreshold'),
    thresholdInput: document.getElementById('thresholdInput'),
    colorCountLabel: document.getElementById('colorCountLabel'),

    // Contexts
    ctx: document.getElementById('previewCanvas').getContext('2d'),
    selectionCtx: document.getElementById('selectionCanvas').getContext('2d'),
    previewContainer: document.querySelector('.preview-container')
};
